# Операції над масивами
> хоча базово всі дані інтерпретуються як масиви, можливо працювавти з двовимірними масивами як алгебраїчними матрицями.

In [7]:
def homework(message):
    print("\n>>>>>", message, "\n")
import numpy as np

> згенеруємо декілька масивів різними способами та виконаємо базові математичні операції.

In [8]:
l = (3, 3)

O = np.ones(l)
R = np.random.random(l)
Z = np.zeros(l)
C = np.arange(l[0])

print(f"""
Віднімання:\n {C - (O + 10)}
Множення:\n {O * R}
Ділення:\n {R / C}
Степінь:\n {C ** Z}
Поріняння:\n {R > 0.5}
Ділення на 0:\n {O / Z}
""")
E = np.eye(l[0])
print(f"""
Створена одинична матриця E:
{E}
Порівняння значень на наявність 1:
{E == 1}
""")
ones_matrix = np.ones(l)
result_matrix = ones_matrix - E
print(f"""
Матриця з одиниць:
{ones_matrix}
Матриця з одиничною діагоналлю:
{E}
Результат віднімання одиничної діагональної матриці від матриці з одиниць:
{result_matrix}
""")


Віднімання:
 [[-11. -10.  -9.]
 [-11. -10.  -9.]
 [-11. -10.  -9.]]
Множення:
 [[0.50706099 0.49265899 0.23874458]
 [0.3668199  0.36178614 0.76950198]
 [0.14656742 0.60985664 0.15299546]]
Ділення:
 [[       inf 0.49265899 0.11937229]
 [       inf 0.36178614 0.38475099]
 [       inf 0.60985664 0.07649773]]
Степінь:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Поріняння:
 [[ True False False]
 [False False  True]
 [False  True False]]
Ділення на 0:
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


Створена одинична матриця E:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Порівняння значень на наявність 1:
[[ True False False]
 [False  True False]
 [False False  True]]


Матриця з одиниць:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Матриця з одиничною діагоналлю:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Результат віднімання одиничної діагональної матриці від матриці з одиниць:
[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]



C:\Users\anime\AppData\Local\Temp\ipykernel_33000\1289728083.py:11: RuntimeWarning: divide by zero encountered in divide
  Ділення:\n {R / C}
C:\Users\anime\AppData\Local\Temp\ipykernel_33000\1289728083.py:14: RuntimeWarning: divide by zero encountered in divide
  Ділення на 0:\n {O / Z}


# Множення матриць

In [9]:
A = np.array([ [1, 2, 3], [2, 2, 2], [3, 3, 3] ])
B = np.array([ [3, 2, 1], [1, 2, 3], [-1, -2, -3] ])
print(f"Маємо два масиви:\n {A} \n {B}")

R = A * B
print(f"Тут виконується поелементне множення:\n {R}")

R = np.dot(A, B)
print(f"Тут, масиви перемножуються як матриці:\n {R}")

MA = np.asmatrix(A)
MB = np.asmatrix(B)

R = MA * MB
print(f"Тут масиви перетворені на матриці і далі перемножуються:\n {R}")

Маємо два масиви:
 [[1 2 3]
 [2 2 2]
 [3 3 3]] 
 [[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
Тут виконується поелементне множення:
 [[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Тут, масиви перемножуються як матриці:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
Тут масиви перетворені на матриці і далі перемножуються:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]


# Вирівнювання розмірностей

In [10]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
C = B[:, np.newaxis]

print(f"Вектор В є рядком {B.shape}: {B} тому додавання буде по рядках:\n {A + B}")

print(f"""Вектор C є стовпцем {C.shape}:
{C}
тому додавання буде по стовпцям:
{A + C}""")

print(f"У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:\n {B + C}")

Вектор В є рядком (3,): [1 2 3] тому додавання буде по рядках:
 [[12 14 16]
 [22 24 26]
 [32 34 36]]
Вектор C є стовпцем (3, 1):
[[1]
 [2]
 [3]]
тому додавання буде по стовпцям:
[[12 13 14]
 [23 24 25]
 [34 35 36]]
У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


# Конкатенація, повторення та зміна форми (shape)

In [11]:
import numpy as np

D = np.ones(3)
Z = np.zeros((3, 1))
B = np.array([[3, 2, 1], [1, 2, 3], [-1, -2, -3]])

D_reshaped = D[:, np.newaxis] 

print(f"""
При конкатенації рядків маємо: {np.concatenate((D_reshaped, D_reshaped), axis=0)}
При конкатенації стовпців маємо:\n{np.concatenate((Z, Z), axis=1)}
Масив D {D} має розмірність {D.shape} тому може виконати операцію конкатенації з В {B} розмірністю {B.shape}:
{np.concatenate((B, D_reshaped), axis=1)}  # Concatenating B and reshaped D along columns
Для конкатенації з С
{B}
де С має розмірність = {B.shape} потрібно змінити розмірність D = {D.shape}
Це можна ось так:
{D[:, np.newaxis].shape}
або
{D.reshape((3, 1)).shape}
в результаті ми можем виконати конкатенацію:
{np.concatenate((B, D.reshape((3, 1))), axis=1)}  # Concatenate B and reshaped D along columns
При повторенні D {D} 2 рази для рядкі та 3 для стовпців будем мати:
{np.tile(D, (2, 3))}
Як бачимо конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: {np.concatenate((D, D))}
- повторення: {np.tile(D, 2)}
Також можна перетворити двовимірний масив A розмірністю {B.shape} на рядок: {B.flatten()} з розмірністю {B.flatten().shape}
""")

array_2d = np.arange(6).reshape(2, 3)
print(f"Створений масив за допомогою arange:\n{array_2d}")

concatenated_rows = np.concatenate((array_2d, array_2d), axis=0)
concatenated_columns = np.concatenate((array_2d, array_2d), axis=1)
print(f"Конкатенація по рядках:\n{concatenated_rows}")
print(f"Конкатенація по стовпцях:\n{concatenated_columns}")

tiled_array = np.tile(array_2d, (2, 2))
print(f"Повторення масиву:\n{tiled_array}")

array_different_shape = np.arange(9).reshape(3, 3)
print(f"Масив з різною кількістю рядків та стовпців:\n{array_different_shape}")

reshaped_array = array_2d.reshape(3, 2)
concatenated_with_reshape = np.concatenate((reshaped_array, array_different_shape), axis=1)
print(f"Конкатенація з перетворенням розмірності:\n{concatenated_with_reshape}")

array_1x12 = np.arange(12).reshape(1, 12)
array_2x6 = np.arange(12).reshape(2, 6)
array_3x4 = np.arange(12).reshape(3, 4)
array_4x3 = np.arange(12).reshape(4, 3)
array_6x2 = np.arange(12).reshape(6, 2)
array_12x1 = np.arange(12).reshape(12, 1)

print(f"""
Можливі варіанти reshape для масиву з 12 елементів:
1x12:\n{array_1x12}
2x6:\n{array_2x6}
3x4:\n{array_3x4}
4x3:\n{array_4x3}
6x2:\n{array_6x2}
12x1:\n{array_12x1}
""")


При конкатенації рядків маємо: [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
При конкатенації стовпців маємо:
[[0. 0.]
 [0. 0.]
 [0. 0.]]
Масив D [1. 1. 1.] має розмірність (3,) тому може виконати операцію конкатенації з В [[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]] розмірністю (3, 3):
[[ 3.  2.  1.  1.]
 [ 1.  2.  3.  1.]
 [-1. -2. -3.  1.]]  # Concatenating B and reshaped D along columns
Для конкатенації з С
[[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
де С має розмірність = (3, 3) потрібно змінити розмірність D = (3,)
Це можна ось так:
(3, 1)
або
(3, 1)
в результаті ми можем виконати конкатенацію:
[[ 3.  2.  1.  1.]
 [ 1.  2.  3.  1.]
 [-1. -2. -3.  1.]]  # Concatenate B and reshaped D along columns
При повторенні D [1. 1. 1.] 2 рази для рядкі та 3 для стовпців будем мати:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Як бачимо конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: [1. 1. 1. 1. 1. 1.]
- повторення: [1. 1. 1. 1. 1. 1.]
Також можна перетворити двовимірни

# Трансформації масивів

In [12]:
O = np.arange(6).reshape(3,2)
O_r = O.reshape((2,3))
O_f = O.flatten()
O_t = O.transpose()
O_fl = np.flip(O)
O_fa = np.flip(O, axis=1)

print(f"""{O}
Змінити розмірність shape {O.shape} на {O_r.shape} при цьому розмір size {O.size} = {O_r.size} та ndim {np.ndim(O)} = {np.ndim(O_r)}:
{O_r}
Також можна перетворити {np.ndim(O)}-х вимірний масив розмірністю {O.shape} на рядок:
{O_f} 
з розмірністю {O_f.shape} при цьому size = {O_f.size} та ndim стане {np.ndim(O_f)}-х вимірним 
Або транспонувати масив щоб він став {O_t.shape} але зверніть увагу на елементи:
{O_t}
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
{O_fl}
Або обернути лише елементи в кожному рядку (або стовпці):
{O_fa}
""")

vector_12 = np.arange(12)
print(f"Вектор з 12 елементів:\n{vector_12}")
print(f"shape: {vector_12.shape}, size: {vector_12.size}, ndim: {np.ndim(vector_12)}")

matrix_3x4 = vector_12.reshape(3, 4)
print(f"Матриця 3x4:\n{matrix_3x4}")
print(f"shape: {matrix_3x4.shape}, size: {matrix_3x4.size}, ndim: {np.ndim(matrix_3x4)}")

transposed_matrix = matrix_3x4.T
print(f"Транспонована матриця:\n{transposed_matrix}")
print(f"shape: {transposed_matrix.shape}, size: {transposed_matrix.size}, ndim: {np.ndim(transposed_matrix)}")

flipped_matrix = np.flip(transposed_matrix)
print(f"Обернена матриця:\n{flipped_matrix}")
print(f"shape: {flipped_matrix.shape}, size: {flipped_matrix.size}, ndim: {np.ndim(flipped_matrix)}")

flattened_array = flipped_matrix.flatten()
print(f"Перетворений назад вектор:\n{flattened_array}")
print(f"shape: {flattened_array.shape}, size: {flattened_array.size}, ndim: {np.ndim(flattened_array)}")

[[0 1]
 [2 3]
 [4 5]]
Змінити розмірність shape (3, 2) на (2, 3) при цьому розмір size 6 = 6 та ndim 2 = 2:
[[0 1 2]
 [3 4 5]]
Також можна перетворити 2-х вимірний масив розмірністю (3, 2) на рядок:
[0 1 2 3 4 5] 
з розмірністю (6,) при цьому size = 6 та ndim стане 1-х вимірним 
Або транспонувати масив щоб він став (2, 3) але зверніть увагу на елементи:
[[0 2 4]
 [1 3 5]]
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
[[5 4]
 [3 2]
 [1 0]]
Або обернути лише елементи в кожному рядку (або стовпці):
[[1 0]
 [3 2]
 [5 4]]

Вектор з 12 елементів:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
shape: (12,), size: 12, ndim: 1
Матриця 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape: (3, 4), size: 12, ndim: 2
Транспонована матриця:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
shape: (4, 3), size: 12, ndim: 2
Обернена матриця:
[[11  7  3]
 [10  6  2]
 [ 9  5  1]
 [ 8  4  0]]
shape: (4, 3), size: 12, ndim: 2
Перетворений назад вектор:
[11  7  3 10  6  2  9  5  1  8  4  0]
s