### Робота з бібліотекою Numpy

In [15]:
def homework(message):
    print("\n>>>>>", message)

In [16]:
import numpy as np
temperature = [20.1, 20.1, 20.2, 20.4]
print(temperature)

t1 = temperature * 5

print(f"При множенні на 5 маємо: {t1}")
homework("Чому маємо такий результат?")
print("Коли ви множите список Python на число, це не є поелементним множенням. Це означає, що весь список повторюється кілька разів, а не кожен його елемент множиться на 5. Тому ви отримуєте один великий список, а не результат множення кожного елемента на 5.\n")

t1 = [ x*5 for x in temperature] 
print(f"Тепер отримаємо: {t1}") 
homework("Чому тепер множення успішне?")
print("При використанні спискового виразу (list comprehension) [x * 5 for x in temperature] кожен елемент списку temperature множиться окремо на 5. Це дозволяє правильно застосувати операцію множення до кожного елемента, що дає коректний результат.\n")

t2 = np.array(temperature)
print("Масив з використанням методів NumPy", t2)

t3 = t2 * 5
print("При множенні на 5 отримуємо:", t3)

[20.1, 20.1, 20.2, 20.4]
При множенні на 5 маємо: [20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4]

>>>>> Чому маємо такий результат?
Коли ви множите список Python на число, це не є поелементним множенням. Це означає, що весь список повторюється кілька разів, а не кожен його елемент множиться на 5. Тому ви отримуєте один великий список, а не результат множення кожного елемента на 5.

Тепер отримаємо: [100.5, 100.5, 101.0, 102.0]

>>>>> Чому тепер множення успішне?
При використанні спискового виразу (list comprehension) [x * 5 for x in temperature] кожен елемент списку temperature множиться окремо на 5. Це дозволяє правильно застосувати операцію множення до кожного елемента, що дає коректний результат.

Масив з використанням методів NumPy [20.1 20.1 20.2 20.4]
При множенні на 5 отримуємо: [100.5 100.5 101.  102. ]


### Вектори, створення та робота з ними

In [17]:
print("Все можна сторити ручну за допомогою методу np.array передавши йому набір значень у вигляді List:")
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(vector_row, "\nВектор має розмір", vector_row.shape)
print(vector_column, "\nВектор має розмір", vector_column.shape)

Все можна сторити ручну за допомогою методу np.array передавши йому набір значень у вигляді List:
[[ 1 -5  3  2  4]] 
Вектор має розмір (1, 5)
[[1]
 [2]
 [3]
 [4]] 
Вектор має розмір (4, 1)


#### Метод arange - генерує послідовність чисел з певним кроком у заданому інтервалі

In [18]:
import numpy as np

start = 5
size_of_vec = 100
x = range(size_of_vec)
a = np.arange(size_of_vec)

print(f"Масив згенерований простим range: {list(x)[:5]} та методом arange: {a[:5]}")
print("Весь діапазон чисел з arange:", list(a))
print("Весь діапазон чисел з range:", list(x))
print("\nУвесь діапазон чисел у масиві `arange` має значення від 0 до 99, що генерується для кожного індексу від 0 до 99.\n")

a = np.arange(start, size_of_vec)
print(f"Можемо задавати початок генерації вектора, перший елемент: {a[0]}")
print(f"Останній елемент у згенерованому масиві: {a[-1]}")
print("\nОстанній діапазон у згенерованому масиві — це значення 99, оскільки початок діапазону визначено як 5, а кінець — 100.\n")

x = range(start, size_of_vec)
print("Те саме, але з вбудованою функцією range:", list(x))
print(f"Число з середини діапазону (наприклад, на індексі 10): {list(x)[10]}")
print("\nЧисло з середини діапазону `range(5, 100)`, зокрема елемент на індексі 10, — це 15, оскільки воно знаходиться в середині заданого діапазону.\n")


x = np.arange(10.4)
print("Згенерований масив з дробовими числами:", x)


x = np.arange(0.5, 4, 0.5)
print("З кроком 0.5:", x)


x = np.arange(0.04, 1.84, 0.08)
print("З кроком 0.08:", x, "\nЗверніть увагу на заокруглення")

x_precise = np.arange(0.0000, 0.0010, 0.0001)
print("Згенероване значення з кроком 0.0001:", x_precise)
print("\nПри кроці 0.0001 у масиві `arange` ми отримуємо значення від 0.0000 до 0.0009 з точністю до чотирьох знаків після коми.\n")

y = x * 2.5
print("Після перемноження з 2.5:", y)

y_raised = (y ** 2) / 0.4
print("Піднесення до степеня та поділене на 0.4:", y_raised)
print("\nПісля піднесення кожного елемента до квадрату та ділення на 0.4, результат стає більшим. Наприклад, перший елемент, 0.1, дає результат 0.025.\n")


Масив згенерований простим range: [0, 1, 2, 3, 4] та методом arange: [0 1 2 3 4]
Весь діапазон чисел з arange: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np

#### Метод linspace - генерує задану кількістю чисел у певному діапазоні, 50 чисел за замовчуванням

In [19]:
import numpy as np

start = 5
size_of_vec = 100

a = np.linspace(start, size_of_vec)
print(f"Згенерували {len(a)} чисел в діапазоні від {a[0]} до {a[-1]}")

print("Кожне друге число згенерованого діапазону:")
for i in range(1, len(a), 2):
    print(a[i])

print("\nМожна зменшити кількість чисел до 5:")
a = np.linspace(start, size_of_vec, 5)
print(a)

a = np.linspace(start, size_of_vec, 100)
print("\nПерші 10 чисел з діапазону:", a[:10])
print("Останні 10 чисел з діапазону:", a[-10:])

print("""
Як бачимо, перше та останнє значення завжди входять у згенерований діапазон.
При цьому автоматично вираховується крок між числами.
Це можна змінити, виключивши останнє значення з діапазону.
""")

a_exclusive = np.linspace(start, size_of_vec, 5, endpoint=False)
print("Згенерований діапазон без останнього значення:", a_exclusive)

print("\nРучний розрахунок кроку між значеннями (без останнього значення):")
manual_step = (size_of_vec - start) / (len(a_exclusive))
print("Крок:", manual_step)

_, sp_1 = np.linspace(start, size_of_vec, 5, endpoint=True, retstep=True)
_, sp_2 = np.linspace(start, size_of_vec, 5, endpoint=False, retstep=True)
print(f"\nДля порівняння, автоматично обчислений крок з включеним останнім значенням: {sp_1}")
print(f"Автоматично обчислений крок без останнього значення: {sp_2}")

print("""
Ми маємо різні кроки через те, що включення або виключення останнього значення змінює відстань між елементами.
При включенні кінцевого значення крок більший, оскільки діапазон треба розділити на менше число інтервалів.
""")


Згенерували 50 чисел в діапазоні від 5.0 до 100.0
Кожне друге число згенерованого діапазону:
6.938775510204081
10.816326530612244
14.693877551020408
18.57142857142857
22.448979591836736
26.3265306122449
30.20408163265306
34.08163265306122
37.95918367346939
41.83673469387755
45.714285714285715
49.59183673469388
53.46938775510204
57.3469387755102
61.224489795918366
65.10204081632654
68.9795918367347
72.85714285714286
76.73469387755102
80.61224489795919
84.48979591836735
88.36734693877551
92.24489795918367
96.12244897959184
100.0

Можна зменшити кількість чисел до 5:
[  5.    28.75  52.5   76.25 100.  ]

Перші 10 чисел з діапазону: [ 5.          5.95959596  6.91919192  7.87878788  8.83838384  9.7979798
 10.75757576 11.71717172 12.67676768 13.63636364]
Останні 10 чисел з діапазону: [ 91.36363636  92.32323232  93.28282828  94.24242424  95.2020202
  96.16161616  97.12121212  98.08080808  99.04040404 100.        ]

Як бачимо, перше та останнє значення завжди входять у згенерований діапазон.
П

### Типи масивів/векторів

In [20]:
import numpy as np

examples = {
    'Скаляр': np.array(1),
    'Вектор Рядок': np.array([1, 2, 3]),
    'Вектор Стовпець': np.array([[1], [2], [3]]),
    'Матриця': np.array([[1, 2], [3, 4], [5, 6]]),
    'Багатовимірна Матриця': np.array([ [[111, 112], [121, 122]],
                                        [[211, 212], [221, 222]],
                                        [[311, 312], [321, 322]] ])
}

for key in examples:
    print(f"Розглядаємо приклад з {key}. \nЗначення x буде: \n", examples[key])
    print(f"Тип {key} x: ", type(examples[key]))
    print(f"Розмірність/вимір {key} x:", np.ndim(examples[key]))
    print(f"Форма {key} x: ", examples[key].shape)
    print(f"Кількість елементів х: {np.size(examples[key])}")
    print("-=-" * 10)

print("""
Функція `np.ndim` повертає кількість осей (вимірів) масиву, а `shape` показує форму кожного з вимірів.
Для векторів ми маємо вимірність 1, оскільки вони є одномірними масивами. У той же час, форма (shape) вектора 
відображає кількість елементів у єдиному вимірі, тоді як форма матриць відображає кількість рядків та стовпців.

Маємо однакове значення `ndim` для векторів та матриць через різні інтерпретації вимірів. Наприклад:
- Вектор рядок має форму (3, ) і вимірність 1.
- Вектор стовпець має форму (3, 1) і вимірність 2, оскільки це матриця з одним стовпцем.

Створимо кілька власних векторів для демонстрації.
""")

vector_row = np.array([4, 5, 6])
vector_column = np.array([[7], [8], [9]])
matrix_example = np.array([[10, 11], [12, 13]])

print("Вектор Рядок:", vector_row)
print("Розмірність:", np.ndim(vector_row))
print("Форма:", vector_row.shape)
print("Кількість елементів:", np.size(vector_row))

print("\nВектор Стовпець:", vector_column)
print("Розмірність:", np.ndim(vector_column))
print("Форма:", vector_column.shape)
print("Кількість елементів:", np.size(vector_column))

print("\nМатриця:", matrix_example)
print("Розмірність:", np.ndim(matrix_example))
print("Форма:", matrix_example.shape)
print("Кількість елементів:", np.size(matrix_example))


Розглядаємо приклад з Скаляр. 
Значення x буде: 
 1
Тип Скаляр x:  <class 'numpy.ndarray'>
Розмірність/вимір Скаляр x: 0
Форма Скаляр x:  ()
Кількість елементів х: 1
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Рядок. 
Значення x буде: 
 [1 2 3]
Тип Вектор Рядок x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Рядок x: 1
Форма Вектор Рядок x:  (3,)
Кількість елементів х: 3
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Стовпець. 
Значення x буде: 
 [[1]
 [2]
 [3]]
Тип Вектор Стовпець x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Стовпець x: 2
Форма Вектор Стовпець x:  (3, 1)
Кількість елементів х: 3
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Матриця. 
Значення x буде: 
 [[1 2]
 [3 4]
 [5 6]]
Тип Матриця x:  <class 'numpy.ndarray'>
Розмірність/вимір Матриця x: 2
Форма Матриця x:  (3, 2)
Кількість елементів х: 6
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Багатовимірна Матриця. 
Значення x буде: 
 [[[111 112]
  [121 122]]

 [[211 

### Багатовимірні масиви, розуміння вимірів

In [21]:
examples = {
    '5 рядків': np.array([[1], [2], [3], [4], [5]]), 
    '5 стовпців': np.array([[1, 2, 3, 4, 5]]),
    '5 елементів': np.array([[[1, 2, 3, 4, 5]]])
    }
for a in examples:
    print(f"Для {a} маємо shape: \n{examples[a].shape} \nта вигляд: \n{examples[a]}")

my_examples = {
    '2 рядки, 3 стовпці': np.array([[10, 20, 30], [40, 50, 60]]),
    '1 рядок, 5 стовпців': np.array([[7, 8, 9, 10, 11]]),
    '3 елементи в одному вимірі': np.array([100, 200, 300]),
    '3D масив з 2 блоків, 2 рядків, 3 стовпців': np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
}

for name, arr in my_examples.items():
    print(f"\nДля масиву '{name}' маємо:")
    print("Форма (shape):", arr.shape)
    print("Масив:\n", arr)


Для 5 рядків маємо shape: 
(5, 1) 
та вигляд: 
[[1]
 [2]
 [3]
 [4]
 [5]]
Для 5 стовпців маємо shape: 
(1, 5) 
та вигляд: 
[[1 2 3 4 5]]
Для 5 елементів маємо shape: 
(1, 1, 5) 
та вигляд: 
[[[1 2 3 4 5]]]

Для масиву '2 рядки, 3 стовпці' маємо:
Форма (shape): (2, 3)
Масив:
 [[10 20 30]
 [40 50 60]]

Для масиву '1 рядок, 5 стовпців' маємо:
Форма (shape): (1, 5)
Масив:
 [[ 7  8  9 10 11]]

Для масиву '3 елементи в одному вимірі' маємо:
Форма (shape): (3,)
Масив:
 [100 200 300]

Для масиву '3D масив з 2 блоків, 2 рядків, 3 стовпців' маємо:
Форма (shape): (2, 2, 3)
Масив:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Indexing and Slicing

In [22]:
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
print(f"""Масив: {F}
Виміри: {F.shape}
Памятаємо, що номерація масивів відбувається з 0.
Тому перший елемент масиву:\n {F[0]}
Другий:\n {F[1]}
Останній, {len(F)}: \n {F[7]}""")

print(f"""Можемо скористатись відємними індексами якщо хочемо доступитись до елементів з кінця масиву.
Але номерація вже з 1.
Тому останній елемент:\n {F[-1]}
Передостанній:\n {F[-2]}""")

print(f"Третій елемент масиву (індекс 2): {F[2]}")
print(f"П'ятий елемент масиву (індекс 4): {F[4]}")

print(f"Передостанній елемент (індекс -2): {F[-2]}")
print(f"Третій елемент з кінця (індекс -3): {F[-3]}")

print(f"Перші три елементи масиву: {F[:3]}")
print(f"Останні три елементи масиву: {F[-3:]}")

print(f"Кожен другий елемент масиву: {F[::2]}")
print(f"Елементи в зворотному порядку: {F[::-1]}")


Масив: [ 1  1  2  3  5  8 13 21]
Виміри: (8,)
Памятаємо, що номерація масивів відбувається з 0.
Тому перший елемент масиву:
 1
Другий:
 1
Останній, 8: 
 21
Можемо скористатись відємними індексами якщо хочемо доступитись до елементів з кінця масиву.
Але номерація вже з 1.
Тому останній елемент:
 21
Передостанній:
 13
Третій елемент масиву (індекс 2): 2
П'ятий елемент масиву (індекс 4): 5
Передостанній елемент (індекс -2): 13
Третій елемент з кінця (індекс -3): 8
Перші три елементи масиву: [1 1 2]
Останні три елементи масиву: [ 8 13 21]
Кожен другий елемент масиву: [ 1  2  5 13]
Елементи в зворотному порядку: [21 13  8  5  3  2  1  1]


In [23]:
A = np.array([ [3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8],
               [7.0, -3.9, 5.1]])

print(f"""Масив:
{A}
Виміри: {A.shape}
Принцип номерації такий самий, ТІЛЬКИ:
Якщо задати одне значення то візьметься цілий рядок:
    Перший рядок: {A[0]}
    Останній рядок: {A[-1]}
Для того щоб взяти цілий стовпець (символ : вказує взяти всі елементи): 
    Перший стовпець: {A[:,0]}
    Останній стовпець: {A[:,-1]}
Потрібно задавати два значення для отримання конкретного елемента: 
    Перший елемент: {A[0][0]} або {A[0, 0]}
    Останній елемент: {A[3][2]} або {A[-1][-1]} або {A[3, -1]}
""")

print("Елементи головної діагоналі:")
for i in range(min(A.shape[0], A.shape[1])): 
    print(f"Елемент [{i}, {i}]: {A[i, i]}")

diag_elements = np.diag(A)
print("Елементи діагоналі за допомогою np.diag:", diag_elements)


Масив:
[[ 3.4  8.7  9.9]
 [ 1.1 -7.8 -0.7]
 [ 4.1 12.3  4.8]
 [ 7.  -3.9  5.1]]
Виміри: (4, 3)
Принцип номерації такий самий, ТІЛЬКИ:
Якщо задати одне значення то візьметься цілий рядок:
    Перший рядок: [3.4 8.7 9.9]
    Останній рядок: [ 7.  -3.9  5.1]
Для того щоб взяти цілий стовпець (символ : вказує взяти всі елементи): 
    Перший стовпець: [3.4 1.1 4.1 7. ]
    Останній стовпець: [ 9.9 -0.7  4.8  5.1]
Потрібно задавати два значення для отримання конкретного елемента: 
    Перший елемент: 3.4 або 3.4
    Останній елемент: 5.1 або 5.1 або 5.1

Елементи головної діагоналі:
Елемент [0, 0]: 3.4
Елемент [1, 1]: -7.8
Елемент [2, 2]: 4.8
Елементи діагоналі за допомогою np.diag: [ 3.4 -7.8  4.8]


In [24]:
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(f"""Масив:
{S}
Виміри: {S.shape}
Беремо декілька елементів: {S[2:5]}
Всі елементи до заданого: {S[:4]}
Всі елементи від заданого до кінця: {S[6:]}
Всі елементи: {S[:]}
""")
last_four = S[-4:]
print("Останні чотири значення масиву:", last_four)

Масив:
[0 1 2 3 4 5 6 7 8 9]
Виміри: (10,)
Беремо декілька елементів: [2 3 4]
Всі елементи до заданого: [0 1 2 3]
Всі елементи від заданого до кінця: [6 7 8 9]
Всі елементи: [0 1 2 3 4 5 6 7 8 9]

Останні чотири значення масиву: [6 7 8 9]


In [25]:
A = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])

print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо декілька рядків: 
{A[0:2]}
Два перші стовпці: 
{A[:, 0:2]}
Два останні рядки:
{A[3:, :]}
Беремо підматрицю (нижні елементи): 
{A[-3:, -3:]}
""")
top_left = A[0:2, 0:2]
print("Підматриця 2x2 з верхнього лівого кута:\n", top_left)

bottom_right = A[-2:, -2:]
print("Підматриця 2x2 з нижнього правого кута:\n", bottom_right)

Масив:
[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]
Виміри: (5, 5)
Беремо декілька рядків: 
[[11 12 13 14 15]
 [21 22 23 24 25]]
Два перші стовпці: 
[[11 12]
 [21 22]
 [31 32]
 [41 42]
 [51 52]]
Два останні рядки:
[[41 42 43 44 45]
 [51 52 53 54 55]]
Беремо підматрицю (нижні елементи): 
[[33 34 35]
 [43 44 45]
 [53 54 55]]

Підматриця 2x2 з верхнього лівого кута:
 [[11 12]
 [21 22]]
Підматриця 2x2 з нижнього правого кута:
 [[44 45]
 [54 55]]


In [26]:
A = np.arange(28).reshape(4, 7)

print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо кожен дугий елемент першого рядка: 
{A[0, ::2]}
Беремо кожен третій елемент першого рядка: 
{A[0, ::3]}
Кожен другий елемент в кожномуу другому рядку: 
{A[::2, ::2]}
Останні три елементи в кожному другому рядку:
{A[::2, 4:]}
Можна повнісню змінити порядок елементів (дзерально обернемо):
{A[::-1, ::-1]}
""")

third_in_second_rows = A[::2, ::3]
print("Кожен третій елемент у кожному другому рядку:\n", third_in_second_rows)

middle_elements = A[:, 2:6]
print("Середні елементи (з індексами 2-5) у всіх рядках:\n", middle_elements)

reversed_rows_every_second_element = A[::-1, ::2]
print("Обернений порядок рядків, але кожен другий елемент у кожному рядку:\n", reversed_rows_every_second_element)

Масив:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
Виміри: (4, 7)
Беремо кожен дугий елемент першого рядка: 
[0 2 4 6]
Беремо кожен третій елемент першого рядка: 
[0 3 6]
Кожен другий елемент в кожномуу другому рядку: 
[[ 0  2  4  6]
 [14 16 18 20]]
Останні три елементи в кожному другому рядку:
[[ 4  5  6]
 [18 19 20]]
Можна повнісню змінити порядок елементів (дзерально обернемо):
[[27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14]
 [13 12 11 10  9  8  7]
 [ 6  5  4  3  2  1  0]]

Кожен третій елемент у кожному другому рядку:
 [[ 0  3  6]
 [14 17 20]]
Середні елементи (з індексами 2-5) у всіх рядках:
 [[ 2  3  4  5]
 [ 9 10 11 12]
 [16 17 18 19]
 [23 24 25 26]]
Обернений порядок рядків, але кожен другий елемент у кожному рядку:
 [[21 23 25 27]
 [14 16 18 20]
 [ 7  9 11 13]
 [ 0  2  4  6]]


In [27]:
A = np.arange(50)
all_even = (A%2==0)
complex = (A<30) & (A/5<2) 

print(f"""Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або {all_even[0]} для {A[0]} або {all_even[1]} для {A[1]}.
Після підставляння умови пошуку парних чисел в масив отримаємо:
{A[all_even]}
Або застосувавти більш комплексну умову з двох порінянь:
{A[complex]}""")

all_odd = (A % 2 != 0)

print(f"Непарні числа з масиву: {A[all_odd]}")

Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або True для 0 або False для 1.
Після підставляння умови пошуку парних чисел в масив отримаємо:
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
Або застосувавти більш комплексну умову з двох порінянь:
[0 1 2 3 4 5 6 7 8 9]
Непарні числа з масиву: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


### Функції для створення матриць: ones, zeros, identity, eye, empty

In [28]:
o = np.ones(5)
z = np.zeros(5)
i = np.identity(5)
e = np.eye(5)
t = np.empty(5)

print(f"""
Всі елементи 1:
{o}
Всі елементи 0:
{z}
Матриця в якої діагональ всі 1:
{i}
Також, діагональ всі 1 (зменшимо вивід):
{e[:2, :2]}
Пуста матриця буде містити набір випадкових чисел які записані у память де був ініціалізований масив:
{t}
""")



Всі елементи 1:
[1. 1. 1. 1. 1.]
Всі елементи 0:
[0. 0. 0. 0. 0.]
Матриця в якої діагональ всі 1:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Також, діагональ всі 1 (зменшимо вивід):
[[1. 0.]
 [0. 1.]]
Пуста матриця буде містити набір випадкових чисел які записані у память де був ініціалізований масив:
[0. 0. 0. 0. 0.]

